import { Injectable } from '@angular/core';
import { Player, League, Match, IPLSeason } from '../models/cricket.models';

@Injectable({ providedIn: 'root' })
export class CricketService {

  getPlayers(): Player[] {
    return [
      { id: 1, name: 'Virat Kohli', country: 'India', countryCode: 'IN', role: 'Batsman', battingStyle: 'Right-handed', bowlingStyle: 'Right-arm medium', age: 35, born: '5 Nov 1988', matches: 292, runs: 13906, average: 58.67, strikeRate: 93.17, wickets: 4, economy: 5.2, fifties: 72, hundreds: 50, avatar: 'VK', bio: 'Virat Kohli is widely regarded as one of the greatest batsmen of all time. He has been ranked as the best ODI batsman in the world by the ICC and is known for his aggressive batting style and exceptional fitness.', iplTeams: ['Royal Challengers Bengaluru'], isFeatured: true },
      { id: 2, name: 'Rohit Sharma', country: 'India', countryCode: 'IN', role: 'Batsman', battingStyle: 'Right-handed', bowlingStyle: 'Right-arm off-break', age: 37, born: '30 Apr 1987', matches: 264, runs: 10709, average: 48.67, strikeRate: 90.3, wickets: 8, economy: 5.5, fifties: 56, hundreds: 31, avatar: 'RS', bio: 'Rohit Sharma is an Indian international cricketer who is the captain of the Indian national cricket team. He is considered one of the best opening batsmen in the world and holds the record for highest individual score in ODIs (264).', iplTeams: ['Mumbai Indians', 'Deccan Chargers'], isFeatured: true },
      { id: 3, name: 'MS Dhoni', country: 'India', countryCode: 'IN', role: 'Wicket-keeper', battingStyle: 'Right-handed', bowlingStyle: 'Right-arm medium', age: 42, born: '7 Jul 1981', matches: 350, runs: 10773, average: 50.57, strikeRate: 87.56, wickets: 0, economy: 0, fifties: 72, hundreds: 10, avatar: 'MD', bio: 'Mahendra Singh Dhoni is a former Indian cricketer and captain of the Indian national cricket team. He is widely regarded as one of the greatest captains in cricket and is famous for his calm demeanor and unorthodox batting style.', iplTeams: ['Chennai Super Kings', 'Rising Pune Supergiants'], isFeatured: true },
      { id: 4, name: 'Jasprit Bumrah', country: 'India', countryCode: 'IN', role: 'Bowler', battingStyle: 'Right-handed', bowlingStyle: 'Right-arm fast', age: 30, born: '6 Dec 1993', matches: 178, runs: 220, average: 8.4, strikeRate: 10.2, wickets: 367, economy: 4.63, fifties: 0, hundreds: 0, avatar: 'JB', bio: 'Jasprit Bumrah is an Indian international cricketer who plays for the Indian national cricket team in all three formats. He is known for his unique bowling action and ability to bowl unplayable yorkers.', iplTeams: ['Mumbai Indians'], isFeatured: true },
      { id: 5, name: 'Hardik Pandya', country: 'India', countryCode: 'IN', role: 'All-rounder', battingStyle: 'Right-handed', bowlingStyle: 'Right-arm fast-medium', age: 30, born: '11 Oct 1993', matches: 123, runs: 1822, average: 35.7, strikeRate: 121.4, wickets: 67, economy: 8.78, fifties: 8, hundreds: 0, avatar: 'HP', bio: 'Hardik Pandya is an Indian international cricketer who plays as an all-rounder. He is known for his aggressive batting and effective medium-fast bowling.', iplTeams: ['Mumbai Indians', 'Gujarat Titans'] },
      { id: 6, name: 'Ravindra Jadeja', country: 'India', countryCode: 'IN', role: 'All-rounder', battingStyle: 'Left-handed', bowlingStyle: 'Slow left-arm orthodox', age: 35, born: '6 Dec 1988', matches: 302, runs: 4600, average: 35.1, strikeRate: 84.3, wickets: 578, economy: 4.8, fifties: 22, hundreds: 3, avatar: 'RJ', bio: 'Ravindra Jadeja is an Indian international cricketer. He is a left-handed batsman and left-arm orthodox spin bowler who is considered one of the best all-rounders in the world.', iplTeams: ['Chennai Super Kings', 'Rajasthan Royals', 'Kochi Tuskers Kerala', 'Gujarat Lions'] },
      { id: 7, name: 'Joe Root', country: 'England', countryCode: 'EN', role: 'Batsman', battingStyle: 'Right-handed', bowlingStyle: 'Right-arm off-break', age: 33, born: '30 Dec 1990', matches: 341, runs: 15600, average: 51.56, strikeRate: 85.3, wickets: 127, economy: 5.1, fifties: 78, hundreds: 35, avatar: 'JR', bio: 'Joe Root is an English international cricketer who is the former captain of the England Test cricket team. He is widely regarded as one of the best batsmen of his generation.', iplTeams: [] },
      { id: 8, name: 'Ben Stokes', country: 'England', countryCode: 'EN', role: 'All-rounder', battingStyle: 'Left-handed', bowlingStyle: 'Right-arm fast-medium', age: 32, born: '4 Jun 1991', matches: 198, runs: 7241, average: 38.6, strikeRate: 95.3, wickets: 212, economy: 5.8, fifties: 39, hundreds: 13, avatar: 'BS', bio: 'Ben Stokes is an English international cricketer who is the current captain of the England Test team. He is one of the best all-rounders in the world and known for his match-winning abilities.', iplTeams: ['Rising Pune Supergiants', 'Rajasthan Royals', 'Chennai Super Kings'] },
      { id: 9, name: 'Steve Smith', country: 'Australia', countryCode: 'AU', role: 'Batsman', battingStyle: 'Right-handed', bowlingStyle: 'Right-arm leg-break', age: 34, born: '2 Jun 1989', matches: 326, runs: 13791, average: 61.77, strikeRate: 83.4, wickets: 44, economy: 5.2, fifties: 66, hundreds: 34, avatar: 'SS', bio: 'Steven Smith is an Australian international cricketer and former captain. He is considered one of the best batsmen in the world across all formats, known for his unorthodox technique and mental resilience.', iplTeams: ['Rajasthan Royals', 'Pune Warriors India', 'Rising Pune Supergiants'] },
      { id: 10, name: 'Pat Cummins', country: 'Australia', countryCode: 'AU', role: 'Bowler', battingStyle: 'Right-handed', bowlingStyle: 'Right-arm fast', age: 31, born: '8 May 1993', matches: 193, runs: 1102, average: 14.7, strikeRate: 64.2, wickets: 377, economy: 4.82, fifties: 1, hundreds: 0, avatar: 'PC', bio: 'Pat Cummins is an Australian international cricketer and the current captain of the Australian national team. He is one of the top-ranked Test bowlers in the world.', iplTeams: ['Kolkata Knight Riders', 'Delhi Capitals'] },
      { id: 11, name: 'Babar Azam', country: 'Pakistan', countryCode: 'PK', role: 'Batsman', battingStyle: 'Right-handed', bowlingStyle: 'Right-arm medium', age: 29, born: '15 Oct 1994', matches: 220, runs: 9840, average: 57.3, strikeRate: 88.7, wickets: 2, economy: 5.8, fifties: 64, hundreds: 20, avatar: 'BA', bio: 'Babar Azam is a Pakistani international cricketer and the former captain of the Pakistan national cricket team. He is considered one of the best batsmen in the world across all three formats.', iplTeams: [] },
      { id: 12, name: 'Shaheen Afridi', country: 'Pakistan', countryCode: 'PK', role: 'Bowler', battingStyle: 'Left-handed', bowlingStyle: 'Left-arm fast', age: 23, born: '6 Apr 2000', matches: 109, runs: 210, average: 8.8, strikeRate: 50.5, wickets: 222, economy: 4.97, fifties: 0, hundreds: 0, avatar: 'SA', bio: 'Shaheen Shah Afridi is a Pakistani international cricketer who plays for the Pakistan national cricket team. He is one of the best fast bowlers in the world, known for his ability to bowl dangerous deliveries.', iplTeams: [] },
      { id: 13, name: 'Kane Williamson', country: 'New Zealand', countryCode: 'NZ', role: 'Batsman', battingStyle: 'Right-handed', bowlingStyle: 'Right-arm off-break', age: 33, born: '8 Aug 1990', matches: 330, runs: 14034, average: 54.45, strikeRate: 82.6, wickets: 52, economy: 4.5, fifties: 82, hundreds: 33, avatar: 'KW', bio: 'Kane Williamson is a New Zealand international cricketer and the former captain. He is regarded as one of the finest batsmen of his generation, known for his elegant stroke play and calm temperament.', iplTeams: ['Sunrisers Hyderabad', 'Gujarat Titans'] },
      { id: 14, name: 'Trent Boult', country: 'New Zealand', countryCode: 'NZ', role: 'Bowler', battingStyle: 'Right-handed', bowlingStyle: 'Left-arm fast-medium', age: 34, born: '22 Jul 1989', matches: 204, runs: 484, average: 7.9, strikeRate: 42.6, wickets: 388, economy: 4.66, fifties: 0, hundreds: 0, avatar: 'TB', bio: 'Trent Boult is a New Zealand international cricketer known for his left-arm swing bowling. He is considered one of the best pace bowlers in the world, particularly effective with the new ball.', iplTeams: ['Mumbai Indians', 'Rajasthan Royals'] },
      { id: 15, name: 'Shakib Al Hasan', country: 'Bangladesh', countryCode: 'BD', role: 'All-rounder', battingStyle: 'Left-handed', bowlingStyle: 'Slow left-arm orthodox', age: 36, born: '24 Mar 1987', matches: 406, runs: 12720, average: 36.4, strikeRate: 80.2, wickets: 703, economy: 4.44, fifties: 69, hundreds: 7, avatar: 'SH', bio: 'Shakib Al Hasan is a Bangladeshi international cricketer. He is widely regarded as the greatest Bangladeshi cricketer of all time and one of the best all-rounders in world cricket.', iplTeams: ['Kolkata Knight Riders', 'Sunrisers Hyderabad'] },
      { id: 16, name: 'Quinton de Kock', country: 'South Africa', countryCode: 'SA', role: 'Wicket-keeper', battingStyle: 'Left-handed', bowlingStyle: 'Right-arm medium', age: 31, born: '17 Dec 1992', matches: 249, runs: 9183, average: 42.3, strikeRate: 95.6, wickets: 0, economy: 0, fifties: 54, hundreds: 17, avatar: 'QD', bio: 'Quinton de Kock is a South African international cricketer who plays as a wicket-keeper batsman. He is known for his aggressive batting style and is one of the best wicketkeeper-batsmen in the world.', iplTeams: ['Mumbai Indians', 'Lucknow Super Giants'] },
      { id: 17, name: 'Kagiso Rabada', country: 'South Africa', countryCode: 'SA', role: 'Bowler', battingStyle: 'Right-handed', bowlingStyle: 'Right-arm fast', age: 28, born: '25 May 1995', matches: 185, runs: 822, average: 11.2, strikeRate: 55.3, wickets: 386, economy: 4.97, fifties: 0, hundreds: 0, avatar: 'KR', bio: 'Kagiso Rabada is a South African international cricketer. He is one of the leading fast bowlers in the world across all formats and is known for his ability to generate pace and movement.', iplTeams: ['Delhi Capitals', 'Punjab Kings'] },
      { id: 18, name: 'Suryakumar Yadav', country: 'India', countryCode: 'IN', role: 'Batsman', battingStyle: 'Right-handed', bowlingStyle: 'Right-arm medium', age: 33, born: '22 Sep 1990', matches: 78, runs: 2503, average: 45.5, strikeRate: 178.2, wickets: 0, economy: 0, fifties: 14, hundreds: 4, avatar: 'SY', bio: 'Suryakumar Yadav is an Indian international cricketer who plays for the Indian national team. He is known for his exceptional 360-degree batting and is the top-ranked T20I batsman in the world.', iplTeams: ['Mumbai Indians', 'Kolkata Knight Riders'] },
      { id: 19, name: 'David Warner', country: 'Australia', countryCode: 'AU', role: 'Batsman', battingStyle: 'Left-handed', bowlingStyle: 'Right-arm leg-break', age: 37, born: '27 Oct 1986', matches: 361, runs: 14694, average: 44.82, strikeRate: 95.3, wickets: 1, economy: 6.2, fifties: 86, hundreds: 26, avatar: 'DW', bio: 'David Warner is an Australian international cricketer and one of the most explosive opening batsmen in all formats. He is known for his aggressive batting style and is a destructive force at the top of the order.', iplTeams: ['Delhi Capitals', 'Sunrisers Hyderabad'] },
      { id: 20, name: 'Rashid Khan', country: 'Afghanistan', countryCode: 'AF', role: 'Bowler', battingStyle: 'Right-handed', bowlingStyle: 'Right-arm leg-break', age: 25, born: '20 Sep 1998', matches: 196, runs: 1567, average: 16.2, strikeRate: 103.4, wickets: 450, economy: 6.17, fifties: 1, hundreds: 0, avatar: 'RK', bio: 'Rashid Khan is an Afghan international cricketer who is one of the most sought-after T20 cricketers in the world. He is a leg-spin bowler known for his sharp googly and effective batting.', iplTeams: ['Sunrisers Hyderabad', 'Gujarat Titans'] },
      { id: 21, name: 'Glenn Maxwell', country: 'Australia', countryCode: 'AU', role: 'All-rounder', battingStyle: 'Right-handed', bowlingStyle: 'Right-arm off-break', age: 35, born: '14 Oct 1988', matches: 214, runs: 5752, average: 33.6, strikeRate: 125.8, wickets: 55, economy: 7.1, fifties: 23, hundreds: 3, avatar: 'GM', bio: 'Glenn Maxwell is an Australian international cricketer known as "The Big Show". He is one of the most destructive batsmen in T20 cricket and a handy off-spin bowler.', iplTeams: ['Mumbai Indians', 'Delhi Daredevils', 'Kings XI Punjab', 'Royal Challengers Bengaluru'] },
      { id: 22, name: 'Shubman Gill', country: 'India', countryCode: 'IN', role: 'Batsman', battingStyle: 'Right-handed', bowlingStyle: 'Right-arm off-break', age: 24, born: '8 Sep 1999', matches: 56, runs: 2467, average: 52.5, strikeRate: 91.4, wickets: 0, economy: 0, fifties: 15, hundreds: 7, avatar: 'SG', bio: 'Shubman Gill is a young Indian international cricketer who has established himself as one of the best young batsmen in the world. He is known for his elegant stroke play and technical proficiency.', iplTeams: ['Kolkata Knight Riders', 'Gujarat Titans'] },
    ];
  }

  getLeagues(): League[] {
    return [
      { id: 1, name: 'ICC Cricket World Cup', shortName: 'CWC', type: 'International', format: 'ODI', country: 'International', region: 'Global', logo: '🏆', color: '#f5a623', description: 'The pinnacle of One Day International cricket, held every 4 years and contested by the best teams in the world.', currentSeason: '2027 (Upcoming)', teams: 10, founded: 1975 },
      { id: 2, name: 'ICC T20 World Cup', shortName: 'T20WC', type: 'International', format: 'T20', country: 'International', region: 'Global', logo: '⚡', color: '#3b82f6', description: 'The premier ICC T20I tournament, featuring the top 20 T20 nations competing for the T20 crown.', currentSeason: '2024 (West Indies & USA)', teams: 20, founded: 2007 },
      { id: 3, name: 'ICC Test Championship', shortName: 'WTC', type: 'International', format: 'Test', country: 'International', region: 'Global', logo: '🎯', color: '#8b5cf6', description: 'The World Test Championship is the elite Test cricket league, determining the best Test cricket nation in the world.', currentSeason: '2023-25 Cycle', teams: 9, founded: 2019 },
      { id: 4, name: 'Indian Premier League', shortName: 'IPL', type: 'Domestic', format: 'T20', country: 'India', region: 'Asia', logo: '🏏', color: '#f59e0b', description: 'The world\'s richest and most watched T20 cricket league, featuring the best players from around the globe playing for 10 franchises.', currentSeason: '2024', teams: 10, founded: 2008 },
      { id: 5, name: 'Big Bash League', shortName: 'BBL', type: 'Domestic', format: 'T20', country: 'Australia', region: 'Oceania', logo: '🔥', color: '#ef4444', description: 'Australia\'s premier domestic T20 competition, played during the summer months and featuring 8 city-based teams.', currentSeason: 'BBL 14 (2024-25)', teams: 8, founded: 2011 },
      { id: 6, name: 'Pakistan Super League', shortName: 'PSL', type: 'Domestic', format: 'T20', country: 'Pakistan', region: 'Asia', logo: '🌟', color: '#10b981', description: 'Pakistan\'s premier domestic T20 competition, showcasing top Pakistani talent alongside international stars.', currentSeason: 'PSL 9 (2024)', teams: 6, founded: 2016 },
      { id: 7, name: 'Caribbean Premier League', shortName: 'CPL', type: 'Domestic', format: 'T20', country: 'West Indies', region: 'Caribbean', logo: '🌴', color: '#f97316', description: 'The Caribbean Premier League is the premier T20 cricket competition of the West Indies, known for its festive atmosphere.', currentSeason: 'CPL 2024', teams: 6, founded: 2013 },
      { id: 8, name: 'The Hundred', shortName: '100', type: 'Domestic', format: 'T20', country: 'England', region: 'Europe', logo: '💯', color: '#ec4899', description: 'England\'s newest cricket competition played in a 100-ball format, designed to attract new audiences to the sport.', currentSeason: '2024', teams: 8, founded: 2021 },
      { id: 9, name: 'Asia Cup', shortName: 'AC', type: 'International', format: 'Mixed', country: 'International', region: 'Asia', logo: '🌏', color: '#14b8a6', description: 'The Asia Cup is a premier cricket tournament contested between the top cricketing nations of Asia.', currentSeason: '2023 (Pakistan/Sri Lanka)', teams: 6, founded: 1984 },
      { id: 10, name: 'The Ashes', shortName: 'ASH', type: 'International', format: 'Test', country: 'England/Australia', region: 'Global', logo: '⚱️', color: '#6366f1', description: 'The iconic Test cricket series between England and Australia, one of cricket\'s greatest and oldest rivalries.', currentSeason: '2025 (Australia)', teams: 2, founded: 1882 },
      { id: 11, name: 'SA20', shortName: 'SA20', type: 'Domestic', format: 'T20', country: 'South Africa', region: 'Africa', logo: '🦁', color: '#22c55e', description: 'South Africa\'s premier T20 league owned by IPL franchise owners, featuring top South African and international talent.', currentSeason: 'SA20 3 (2025)', teams: 6, founded: 2023 },
      { id: 12, name: 'Champions Trophy', shortName: 'CT', type: 'International', format: 'ODI', country: 'International', region: 'Global', logo: '🏅', color: '#a78bfa', description: 'The ICC Champions Trophy is the second-most important ODI tournament after the World Cup, featuring the top 8 ranked ODI nations.', currentSeason: '2025 (Pakistan)', teams: 8, founded: 1998 },
    ];
  }

  getMatches(): Match[] {
    return [
      { id: 1, team1: 'India', team2: 'Australia', date: '2024-10-05', venue: 'MA Chidambaram Stadium, Chennai', format: 'Test', status: 'Completed', result: 'India won by 280 runs', leagueId: 3 },
      { id: 2, team1: 'England', team2: 'Pakistan', date: '2024-10-12', venue: 'Lord\'s Cricket Ground, London', format: 'ODI', status: 'Completed', result: 'England won by 6 wickets', leagueId: 1 },
      { id: 3, team1: 'South Africa', team2: 'New Zealand', date: '2025-01-15', venue: 'Newlands, Cape Town', format: 'T20', status: 'Upcoming', leagueId: 2 },
      { id: 4, team1: 'West Indies', team2: 'Sri Lanka', date: '2025-02-01', venue: 'Kensington Oval, Barbados', format: 'ODI', status: 'Upcoming', leagueId: 9 },
      { id: 5, team1: 'Mumbai Indians', team2: 'Chennai Super Kings', date: '2024-04-10', venue: 'Wankhede Stadium, Mumbai', format: 'T20', status: 'Completed', result: 'Mumbai Indians won by 5 wickets', leagueId: 4 },
      { id: 6, team1: 'Royal Challengers Bengaluru', team2: 'Kolkata Knight Riders', date: '2024-04-21', venue: 'M Chinnaswamy Stadium, Bengaluru', format: 'T20', status: 'Completed', result: 'KKR won by 7 runs', leagueId: 4 },
    ];
  }

  getIPLSeasons(): IPLSeason[] {
    return [
      { year: 2024, winner: 'Kolkata Knight Riders', winnerColor: '#4a0e8f', runnerUp: 'Sunrisers Hyderabad', finalVenue: 'MA Chidambaram Stadium, Chennai', manOfTheSeries: 'Sunil Narine', topScorer: 'Virat Kohli (741)', topWicketTaker: 'Harshal Patel (24)', notablePlayers: ['Sunil Narine', 'Phil Salt', 'Andre Russell', 'Varun Chakravarthy'], rankings: [ { rank: 1, team: 'Kolkata Knight Riders', shortName: 'KKR', color: '#4a0e8f', played: 14, won: 9, lost: 5, points: 20, nrr: '+1.428' }, { rank: 2, team: 'Sunrisers Hyderabad', shortName: 'SRH', color: '#f97316', played: 14, won: 10, lost: 4, points: 20, nrr: '+0.648' }, { rank: 3, team: 'Rajasthan Royals', shortName: 'RR', color: '#ec4899', played: 14, won: 9, lost: 5, points: 18, nrr: '+0.288' }, { rank: 4, team: 'Royal Challengers Bengaluru', shortName: 'RCB', color: '#dc2626', played: 14, won: 7, lost: 7, points: 14, nrr: '+0.397' }, { rank: 5, team: 'Chennai Super Kings', shortName: 'CSK', color: '#eab308', played: 14, won: 7, lost: 7, points: 14, nrr: '-0.021' }, { rank: 6, team: 'Delhi Capitals', shortName: 'DC', color: '#3b82f6', played: 14, won: 7, lost: 7, points: 14, nrr: '-0.382' }, { rank: 7, team: 'Lucknow Super Giants', shortName: 'LSG', color: '#0891b2', played: 14, won: 7, lost: 7, points: 14, nrr: '-0.459' }, { rank: 8, team: 'Gujarat Titans', shortName: 'GT', color: '#1d4ed8', played: 14, won: 5, lost: 9, points: 10, nrr: '-0.386' }, { rank: 9, team: 'Mumbai Indians', shortName: 'MI', color: '#1d4ed8', played: 14, won: 4, lost: 10, points: 8, nrr: '-0.559' }, { rank: 10, team: 'Punjab Kings', shortName: 'PBKS', color: '#dc2626', played: 14, won: 4, lost: 10, points: 8, nrr: '-0.956' } ] },
      { year: 2023, winner: 'Chennai Super Kings', winnerColor: '#eab308', runnerUp: 'Gujarat Titans', finalVenue: 'Narendra Modi Stadium, Ahmedabad', manOfTheSeries: 'Shubman Gill', topScorer: 'Shubman Gill (890)', topWicketTaker: 'Mohammad Shami (28)', notablePlayers: ['Shubman Gill', 'MS Dhoni', 'Devon Conway', 'Ravindra Jadeja'], rankings: [ { rank: 1, team: 'Gujarat Titans', shortName: 'GT', color: '#1d4ed8', played: 14, won: 10, lost: 4, points: 20, nrr: '+0.916' }, { rank: 2, team: 'Chennai Super Kings', shortName: 'CSK', color: '#eab308', played: 14, won: 8, lost: 6, points: 17, nrr: '+0.652' }, { rank: 3, team: 'Lucknow Super Giants', shortName: 'LSG', color: '#0891b2', played: 14, won: 9, lost: 5, points: 18, nrr: '+0.578' }, { rank: 4, team: 'Mumbai Indians', shortName: 'MI', color: '#1d4ed8', played: 14, won: 8, lost: 6, points: 16, nrr: '+0.441' }, { rank: 5, team: 'Rajasthan Royals', shortName: 'RR', color: '#ec4899', played: 14, won: 7, lost: 7, points: 14, nrr: '+0.096' }, { rank: 6, team: 'Royal Challengers Bengaluru', shortName: 'RCB', color: '#dc2626', played: 14, won: 7, lost: 7, points: 14, nrr: '+0.009' }, { rank: 7, team: 'Kolkata Knight Riders', shortName: 'KKR', color: '#4a0e8f', played: 14, won: 6, lost: 8, points: 12, nrr: '-0.259' }, { rank: 8, team: 'Delhi Capitals', shortName: 'DC', color: '#3b82f6', played: 14, won: 5, lost: 9, points: 10, nrr: '-0.795' }, { rank: 9, team: 'Punjab Kings', shortName: 'PBKS', color: '#dc2626', played: 14, won: 4, lost: 10, points: 8, nrr: '-0.404' }, { rank: 10, team: 'Sunrisers Hyderabad', shortName: 'SRH', color: '#f97316', played: 14, won: 4, lost: 10, points: 8, nrr: '-1.234' } ] },
      { year: 2022, winner: 'Gujarat Titans', winnerColor: '#1d4ed8', runnerUp: 'Rajasthan Royals', finalVenue: 'Narendra Modi Stadium, Ahmedabad', manOfTheSeries: 'Hardik Pandya', topScorer: 'Jos Buttler (863)', topWicketTaker: 'Yuzvendra Chahal (27)', notablePlayers: ['Hardik Pandya', 'Jos Buttler', 'Shubman Gill', 'Sanju Samson'], rankings: [ { rank: 1, team: 'Gujarat Titans', shortName: 'GT', color: '#1d4ed8', played: 14, won: 10, lost: 4, points: 20, nrr: '+0.316' }, { rank: 2, team: 'Rajasthan Royals', shortName: 'RR', color: '#ec4899', played: 14, won: 9, lost: 5, points: 18, nrr: '+0.298' }, { rank: 3, team: 'Lucknow Super Giants', shortName: 'LSG', color: '#0891b2', played: 14, won: 9, lost: 5, points: 18, nrr: '+0.251' }, { rank: 4, team: 'Royal Challengers Bengaluru', shortName: 'RCB', color: '#dc2626', played: 14, won: 8, lost: 6, points: 16, nrr: '-0.253' }, { rank: 5, team: 'Delhi Capitals', shortName: 'DC', color: '#3b82f6', played: 14, won: 7, lost: 7, points: 14, nrr: '+0.204' }, { rank: 6, team: 'Punjab Kings', shortName: 'PBKS', color: '#dc2626', played: 14, won: 7, lost: 7, points: 14, nrr: '-0.304' }, { rank: 7, team: 'Kolkata Knight Riders', shortName: 'KKR', color: '#4a0e8f', played: 14, won: 6, lost: 8, points: 12, nrr: '+0.146' }, { rank: 8, team: 'Sunrisers Hyderabad', shortName: 'SRH', color: '#f97316', played: 14, won: 6, lost: 8, points: 12, nrr: '-0.384' }, { rank: 9, team: 'Chennai Super Kings', shortName: 'CSK', color: '#eab308', played: 14, won: 4, lost: 10, points: 8, nrr: '-0.382' }, { rank: 10, team: 'Mumbai Indians', shortName: 'MI', color: '#1d4ed8', played: 14, won: 4, lost: 10, points: 8, nrr: '-0.508' } ] },
      { year: 2021, winner: 'Chennai Super Kings', winnerColor: '#eab308', runnerUp: 'Kolkata Knight Riders', finalVenue: 'Dubai International Cricket Stadium', manOfTheSeries: 'Harshal Patel', topScorer: 'Ruturaj Gaikwad (635)', topWicketTaker: 'Harshal Patel (32)', notablePlayers: ['Ruturaj Gaikwad', 'Faf du Plessis', 'Suresh Raina', 'Deepak Chahar'], rankings: [ { rank: 1, team: 'Delhi Capitals', shortName: 'DC', color: '#3b82f6', played: 14, won: 10, lost: 4, points: 20, nrr: '+0.481' }, { rank: 2, team: 'Chennai Super Kings', shortName: 'CSK', color: '#eab308', played: 14, won: 9, lost: 5, points: 18, nrr: '+0.455' }, { rank: 3, team: 'Royal Challengers Bengaluru', shortName: 'RCB', color: '#dc2626', played: 14, won: 9, lost: 5, points: 18, nrr: '+0.171' }, { rank: 4, team: 'Kolkata Knight Riders', shortName: 'KKR', color: '#4a0e8f', played: 14, won: 7, lost: 7, points: 14, nrr: '+0.587' }, { rank: 5, team: 'Mumbai Indians', shortName: 'MI', color: '#1d4ed8', played: 14, won: 7, lost: 7, points: 14, nrr: '+0.103' }, { rank: 6, team: 'Punjab Kings', shortName: 'PBKS', color: '#dc2626', played: 14, won: 6, lost: 8, points: 12, nrr: '+0.007' }, { rank: 7, team: 'Rajasthan Royals', shortName: 'RR', color: '#ec4899', played: 14, won: 5, lost: 9, points: 10, nrr: '-0.994' }, { rank: 8, team: 'Sunrisers Hyderabad', shortName: 'SRH', color: '#f97316', played: 14, won: 3, lost: 11, points: 6, nrr: '-1.265' } ] },
      { year: 2020, winner: 'Mumbai Indians', winnerColor: '#1d4ed8', runnerUp: 'Delhi Capitals', finalVenue: 'Dubai International Cricket Stadium', manOfTheSeries: 'Jofra Archer', topScorer: 'KL Rahul (670)', topWicketTaker: 'Kagiso Rabada (30)', notablePlayers: ['Rohit Sharma', 'Quinton de Kock', 'Jasprit Bumrah', 'Trent Boult'], rankings: [ { rank: 1, team: 'Mumbai Indians', shortName: 'MI', color: '#1d4ed8', played: 14, won: 9, lost: 5, points: 18, nrr: '+1.107' }, { rank: 2, team: 'Delhi Capitals', shortName: 'DC', color: '#3b82f6', played: 14, won: 8, lost: 6, points: 16, nrr: '+0.481' }, { rank: 3, team: 'Sunrisers Hyderabad', shortName: 'SRH', color: '#f97316', played: 14, won: 7, lost: 7, points: 14, nrr: '+0.600' }, { rank: 4, team: 'Royal Challengers Bengaluru', shortName: 'RCB', color: '#dc2626', played: 14, won: 7, lost: 7, points: 14, nrr: '+0.159' }, { rank: 5, team: 'Kolkata Knight Riders', shortName: 'KKR', color: '#4a0e8f', played: 14, won: 7, lost: 7, points: 14, nrr: '+0.028' }, { rank: 6, team: 'Rajasthan Royals', shortName: 'RR', color: '#ec4899', played: 14, won: 6, lost: 8, points: 12, nrr: '-0.593' }, { rank: 7, team: 'Chennai Super Kings', shortName: 'CSK', color: '#eab308', played: 14, won: 6, lost: 8, points: 12, nrr: '-0.455' }, { rank: 8, team: 'Kings XI Punjab', shortName: 'KXIP', color: '#dc2626', played: 14, won: 6, lost: 8, points: 12, nrr: '-0.099' } ] },
      { year: 2019, winner: 'Mumbai Indians', winnerColor: '#1d4ed8', runnerUp: 'Chennai Super Kings', finalVenue: 'Rajiv Gandhi International Cricket Stadium, Hyderabad', manOfTheSeries: 'Andre Russell', topScorer: 'David Warner (692)', topWicketTaker: 'Imran Tahir (26)', notablePlayers: ['Rohit Sharma', 'Kieron Pollard', 'Andre Russell', 'Jasprit Bumrah'], rankings: [ { rank: 1, team: 'Mumbai Indians', shortName: 'MI', color: '#1d4ed8', played: 14, won: 9, lost: 5, points: 18, nrr: '+0.421' }, { rank: 2, team: 'Chennai Super Kings', shortName: 'CSK', color: '#eab308', played: 14, won: 9, lost: 5, points: 18, nrr: '+0.147' }, { rank: 3, team: 'Delhi Capitals', shortName: 'DC', color: '#3b82f6', played: 14, won: 9, lost: 5, points: 18, nrr: '-0.085' }, { rank: 4, team: 'Sunrisers Hyderabad', shortName: 'SRH', color: '#f97316', played: 14, won: 6, lost: 8, points: 12, nrr: '-0.415' }, { rank: 5, team: 'Kolkata Knight Riders', shortName: 'KKR', color: '#4a0e8f', played: 14, won: 6, lost: 8, points: 12, nrr: '-0.070' }, { rank: 6, team: 'Kings XI Punjab', shortName: 'KXIP', color: '#dc2626', played: 14, won: 6, lost: 8, points: 12, nrr: '+0.060' }, { rank: 7, team: 'Rajasthan Royals', shortName: 'RR', color: '#ec4899', played: 14, won: 4, lost: 10, points: 8, nrr: '-0.445' }, { rank: 8, team: 'Royal Challengers Bengaluru', shortName: 'RCB', color: '#dc2626', played: 14, won: 5, lost: 9, points: 10, nrr: '-0.607' } ] },
      { year: 2018, winner: 'Chennai Super Kings', winnerColor: '#eab308', runnerUp: 'Sunrisers Hyderabad', finalVenue: 'Wankhede Stadium, Mumbai', manOfTheSeries: 'Sunil Narine', topScorer: 'Kane Williamson (735)', topWicketTaker: 'Andrew Tye (24)', notablePlayers: ['Ambati Rayudu', 'Shane Watson', 'Faf du Plessis', 'MS Dhoni'], rankings: [ { rank: 1, team: 'Sunrisers Hyderabad', shortName: 'SRH', color: '#f97316', played: 14, won: 9, lost: 5, points: 18, nrr: '+0.501' }, { rank: 2, team: 'Chennai Super Kings', shortName: 'CSK', color: '#eab308', played: 14, won: 9, lost: 5, points: 18, nrr: '+0.253' }, { rank: 3, team: 'Kolkata Knight Riders', shortName: 'KKR', color: '#4a0e8f', played: 14, won: 8, lost: 6, points: 16, nrr: '+0.096' }, { rank: 4, team: 'Rajasthan Royals', shortName: 'RR', color: '#ec4899', played: 14, won: 7, lost: 7, points: 14, nrr: '-0.250' }, { rank: 5, team: 'Mumbai Indians', shortName: 'MI', color: '#1d4ed8', played: 14, won: 6, lost: 8, points: 12, nrr: '+0.317' }, { rank: 6, team: 'Delhi Daredevils', shortName: 'DD', color: '#3b82f6', played: 14, won: 5, lost: 9, points: 10, nrr: '-0.512' }, { rank: 7, team: 'Kings XI Punjab', shortName: 'KXIP', color: '#dc2626', played: 14, won: 6, lost: 8, points: 12, nrr: '-0.100' }, { rank: 8, team: 'Royal Challengers Bengaluru', shortName: 'RCB', color: '#dc2626', played: 14, won: 6, lost: 8, points: 12, nrr: '-0.350' } ] },
      { year: 2016, winner: 'Sunrisers Hyderabad', winnerColor: '#f97316', runnerUp: 'Royal Challengers Bengaluru', finalVenue: 'M Chinnaswamy Stadium, Bengaluru', manOfTheSeries: 'Virat Kohli', topScorer: 'Virat Kohli (973)', topWicketTaker: 'Bhuvneshwar Kumar (23)', notablePlayers: ['Virat Kohli', 'AB de Villiers', 'David Warner', 'Chris Gayle'], rankings: [ { rank: 1, team: 'Sunrisers Hyderabad', shortName: 'SRH', color: '#f97316', played: 14, won: 9, lost: 5, points: 18, nrr: '+0.573' }, { rank: 2, team: 'Royal Challengers Bengaluru', shortName: 'RCB', color: '#dc2626', played: 14, won: 8, lost: 6, points: 16, nrr: '+0.293' }, { rank: 3, team: 'Gujarat Lions', shortName: 'GL', color: '#f97316', played: 14, won: 9, lost: 5, points: 18, nrr: '+0.317' }, { rank: 4, team: 'Kolkata Knight Riders', shortName: 'KKR', color: '#4a0e8f', played: 14, won: 7, lost: 7, points: 14, nrr: '+0.296' }, { rank: 5, team: 'Mumbai Indians', shortName: 'MI', color: '#1d4ed8', played: 14, won: 7, lost: 7, points: 14, nrr: '-0.012' }, { rank: 6, team: 'Delhi Daredevils', shortName: 'DD', color: '#3b82f6', played: 14, won: 7, lost: 7, points: 14, nrr: '-0.186' }, { rank: 7, team: 'Kings XI Punjab', shortName: 'KXIP', color: '#dc2626', played: 14, won: 4, lost: 10, points: 8, nrr: '-0.541' }, { rank: 8, team: 'Rising Pune Supergiants', shortName: 'RPS', color: '#a855f7', played: 14, won: 5, lost: 9, points: 10, nrr: '-0.693' } ] },
      { year: 2013, winner: 'Mumbai Indians', winnerColor: '#1d4ed8', runnerUp: 'Chennai Super Kings', finalVenue: 'Eden Gardens, Kolkata', manOfTheSeries: 'Shane Watson', topScorer: 'Michael Hussey (733)', topWicketTaker: 'Dwayne Bravo (32)', notablePlayers: ['Rohit Sharma', 'Sachin Tendulkar', 'Kieron Pollard', 'Lasith Malinga'], rankings: [ { rank: 1, team: 'Mumbai Indians', shortName: 'MI', color: '#1d4ed8', played: 16, won: 11, lost: 5, points: 22, nrr: '+0.638' }, { rank: 2, team: 'Chennai Super Kings', shortName: 'CSK', color: '#eab308', played: 16, won: 11, lost: 5, points: 22, nrr: '+0.509' }, { rank: 3, team: 'Rajasthan Royals', shortName: 'RR', color: '#ec4899', played: 16, won: 10, lost: 6, points: 20, nrr: '+0.336' }, { rank: 4, team: 'Sunrisers Hyderabad', shortName: 'SRH', color: '#f97316', played: 16, won: 9, lost: 7, points: 18, nrr: '+0.183' }, { rank: 5, team: 'Royal Challengers Bengaluru', shortName: 'RCB', color: '#dc2626', played: 16, won: 9, lost: 7, points: 18, nrr: '+0.046' }, { rank: 6, team: 'Kolkata Knight Riders', shortName: 'KKR', color: '#4a0e8f', played: 16, won: 7, lost: 9, points: 14, nrr: '-0.105' }, { rank: 7, team: 'Delhi Daredevils', shortName: 'DD', color: '#3b82f6', played: 16, won: 5, lost: 11, points: 10, nrr: '-0.619' }, { rank: 8, team: 'Kings XI Punjab', shortName: 'KXIP', color: '#dc2626', played: 16, won: 5, lost: 11, points: 10, nrr: '-0.689' }, { rank: 9, team: 'Pune Warriors', shortName: 'PWI', color: '#14b8a6', played: 16, won: 2, lost: 14, points: 4, nrr: '-0.839' } ] },
      { year: 2008, winner: 'Rajasthan Royals', winnerColor: '#ec4899', runnerUp: 'Chennai Super Kings', finalVenue: 'DY Patil Stadium, Mumbai', manOfTheSeries: 'Shane Watson', topScorer: 'Shaun Marsh (616)', topWicketTaker: 'Sohail Tanvir (22)', notablePlayers: ['Shane Warne', 'Shane Watson', 'Yusuf Pathan', 'Sohail Tanvir'], rankings: [ { rank: 1, team: 'Rajasthan Royals', shortName: 'RR', color: '#ec4899', played: 16, won: 11, lost: 5, points: 22, nrr: '+0.971' }, { rank: 2, team: 'Chennai Super Kings', shortName: 'CSK', color: '#eab308', played: 16, won: 9, lost: 7, points: 18, nrr: '+0.649' }, { rank: 3, team: 'Delhi Daredevils', shortName: 'DD', color: '#3b82f6', played: 16, won: 9, lost: 7, points: 18, nrr: '+0.406' }, { rank: 4, team: 'Kings XI Punjab', shortName: 'KXIP', color: '#dc2626', played: 16, won: 8, lost: 8, points: 16, nrr: '+0.100' }, { rank: 5, team: 'Mumbai Indians', shortName: 'MI', color: '#1d4ed8', played: 16, won: 7, lost: 9, points: 14, nrr: '-0.080' }, { rank: 6, team: 'Royal Challengers Bengaluru', shortName: 'RCB', color: '#dc2626', played: 16, won: 4, lost: 12, points: 8, nrr: '-0.571' }, { rank: 7, team: 'Kolkata Knight Riders', shortName: 'KKR', color: '#4a0e8f', played: 16, won: 6, lost: 10, points: 12, nrr: '-0.657' }, { rank: 8, team: 'Deccan Chargers', shortName: 'DC', color: '#f97316', played: 16, won: 2, lost: 14, points: 4, nrr: '-0.883' } ] },
    ];
  }

  getIPLPlayersByYear(year: number): { name: string; team: string; role: string; country: string; runs?: number; wickets?: number }[] {
    const squads: Record<number, { name: string; team: string; role: string; country: string; runs?: number; wickets?: number }[]> = {
      2024: [
        { name: 'Rohit Sharma', team: 'Mumbai Indians', role: 'Batsman', country: 'India', runs: 417 },
        { name: 'Virat Kohli', team: 'Royal Challengers Bengaluru', role: 'Batsman', country: 'India', runs: 741 },
        { name: 'MS Dhoni', team: 'Chennai Super Kings', role: 'Wicket-keeper', country: 'India', runs: 161 },
        { name: 'Sunil Narine', team: 'Kolkata Knight Riders', role: 'All-rounder', country: 'West Indies', runs: 488, wickets: 17 },
        { name: 'Phil Salt', team: 'Kolkata Knight Riders', role: 'Batsman', country: 'England', runs: 435 },
        { name: 'Heinrich Klaasen', team: 'Sunrisers Hyderabad', role: 'Wicket-keeper', country: 'South Africa', runs: 479 },
        { name: 'Travis Head', team: 'Sunrisers Hyderabad', role: 'Batsman', country: 'Australia', runs: 567 },
        { name: 'Pat Cummins', team: 'Sunrisers Hyderabad', role: 'Bowler', country: 'Australia', wickets: 17 },
        { name: 'Jasprit Bumrah', team: 'Mumbai Indians', role: 'Bowler', country: 'India', wickets: 15 },
        { name: 'Harshal Patel', team: 'Punjab Kings', role: 'Bowler', country: 'India', wickets: 24 },
        { name: 'Andre Russell', team: 'Kolkata Knight Riders', role: 'All-rounder', country: 'West Indies', runs: 222, wickets: 19 },
        { name: 'Rishabh Pant', team: 'Delhi Capitals', role: 'Wicket-keeper', country: 'India', runs: 446 },
      ],
      2023: [
        { name: 'Shubman Gill', team: 'Gujarat Titans', role: 'Batsman', country: 'India', runs: 890 },
        { name: 'MS Dhoni', team: 'Chennai Super Kings', role: 'Wicket-keeper', country: 'India', runs: 238 },
        { name: 'Faf du Plessis', team: 'Royal Challengers Bengaluru', role: 'Batsman', country: 'South Africa', runs: 730 },
        { name: 'Devon Conway', team: 'Chennai Super Kings', role: 'Batsman', country: 'New Zealand', runs: 672 },
        { name: 'Ruturaj Gaikwad', team: 'Chennai Super Kings', role: 'Batsman', country: 'India', runs: 590 },
        { name: 'Mohammed Shami', team: 'Gujarat Titans', role: 'Bowler', country: 'India', wickets: 28 },
        { name: 'Ravindra Jadeja', team: 'Chennai Super Kings', role: 'All-rounder', country: 'India', runs: 380, wickets: 12 },
        { name: 'Rashid Khan', team: 'Gujarat Titans', role: 'Bowler', country: 'Afghanistan', wickets: 27 },
        { name: 'Virat Kohli', team: 'Royal Challengers Bengaluru', role: 'Batsman', country: 'India', runs: 639 },
        { name: 'KL Rahul', team: 'Lucknow Super Giants', role: 'Wicket-keeper', country: 'India', runs: 520 },
        { name: 'Nicholas Pooran', team: 'Lucknow Super Giants', role: 'Wicket-keeper', country: 'West Indies', runs: 531 },
        { name: 'Yuzvendra Chahal', team: 'Rajasthan Royals', role: 'Bowler', country: 'India', wickets: 21 },
      ],
      2022: [
        { name: 'Jos Buttler', team: 'Rajasthan Royals', role: 'Batsman', country: 'England', runs: 863 },
        { name: 'Hardik Pandya', team: 'Gujarat Titans', role: 'All-rounder', country: 'India', runs: 487, wickets: 8 },
        { name: 'Shubman Gill', team: 'Gujarat Titans', role: 'Batsman', country: 'India', runs: 483 },
        { name: 'Sanju Samson', team: 'Rajasthan Royals', role: 'Wicket-keeper', country: 'India', runs: 458 },
        { name: 'Yuzvendra Chahal', team: 'Rajasthan Royals', role: 'Bowler', country: 'India', wickets: 27 },
        { name: 'Kagiso Rabada', team: 'Punjab Kings', role: 'Bowler', country: 'South Africa', wickets: 23 },
        { name: 'David Warner', team: 'Delhi Capitals', role: 'Batsman', country: 'Australia', runs: 432 },
        { name: 'Quinton de Kock', team: 'Lucknow Super Giants', role: 'Wicket-keeper', country: 'South Africa', runs: 508 },
        { name: 'Rashid Khan', team: 'Gujarat Titans', role: 'Bowler', country: 'Afghanistan', wickets: 20 },
        { name: 'Faf du Plessis', team: 'Royal Challengers Bengaluru', role: 'Batsman', country: 'South Africa', runs: 468 },
        { name: 'Virat Kohli', team: 'Royal Challengers Bengaluru', role: 'Batsman', country: 'India', runs: 341 },
        { name: 'Kane Williamson', team: 'Sunrisers Hyderabad', role: 'Batsman', country: 'New Zealand', runs: 216 },
      ],
    };
    return squads[year] || squads[2024];
  }
}
